const fs = require('fs');
const src = fs.readFileSync(process.argv[2] || require('path').join(__dirname, '../dist/project/Main.dc.html'), 'utf8');
const js = src.split('data-dc-script')[1].split('>').slice(1).join('>').split('</script>')[0];
global.DCLogic = class { constructor(p) { this.props = p || {}; } setState(u) { this.state = { ...this.state, ...u }; } };
global.setTimeout = () => 0; global.clearTimeout = () => {};
const C = eval('(' + js.trim().replace(/^class Component/, 'class') + ')');
const c = new C({});
let v = c.renderVals();
const markup = src.slice(src.indexOf('<x-dc>'), src.indexOf('</x-dc>'));
const loopVars = new Set([...markup.matchAll(/as="(\w+)"/g)].map((m) => m[1]));
const holes = [...new Set([...markup.matchAll(/\{\{\s*([\w.$]+)\s*\}\}/g)].map((m) => m[1]))].filter((h) => !loopVars.has(h.split('.')[0]) && !/^(true|false)$/.test(h));
const miss = holes.filter((h) => !(h.split('.')[0] in v));
console.log(miss.length ? 'MISSING holes: ' + miss.join(', ') : 'top-level holes ok (' + holes.length + ')');
for (const banned of ['kpis', 'distBtns', 'ownBtn', 'dock', 'hasPanel', 'dr.']) if (markup.includes('{{' + banned)) console.log('LEFTOVER', banned);
const show = (tag) => { v = c.renderVals(); const p = v.panel; console.log('\n[' + tag + '] crumbs:', p.crumbs.map((x) => x.label).join(' › '), '| title:', p.title);
  console.log('   stats:', p.stats.map((s) => s.label + ' ' + s.value).join(' | '));
  if (p.notUnit) p.sections.forEach((s) => console.log('   ' + (s.isOpen ? '▾' : '▸'), s.title.padEnd(16), s.summary.padEnd(42), 'rows', s.rows.length + (s.hasMore ? '+' + s.more : ''))); };
show('portfolio, PM');
console.log('   parcels:', v.parcels.length, '| buildings', v.objects.filter((o) => o.isB).length);
v.parcels.find((p) => p.name === 'Oakwood Gardens').pick(); show('ground under Oakwood clicked');
console.log('   buildings list:', v.panel.blds.map((b) => b.addr + ' (' + b.summary + ')').join(' ; '));
v.objects.find((o) => o.isB && o.title.startsWith('3303 Wood')).pick(); show('building 3303 Wood clicked');
console.log('   floors:', v.panel.bldg.floors.map((f) => f.label + ':' + f.units.map((t) => t.u).join(',')).join(' | '));
const occ = v.panel.sections.find((s) => s.key === 'occ'); console.log('   occupancy section at building scope:', occ.summary, '| empty msg:', occ.empty ? occ.emptyText : '');
v.panel.bldg.floors[0].units[0].go(); v = c.renderVals();
console.log('\n[unit] ', v.panel.title, '|', v.panel.sub, '| tenant', v.panel.unit.tenant, '| phone', v.panel.unit.phone, '| issues', v.panel.unit.count);
c.setState({ role: 'va', picked: null, pickedB: null, pickedU: null }); show('portfolio, VA');
c.setState({ picked: 'Hilltop Townhomes' }); show('Hilltop, VA');
v.panel.sections.find((s) => s.key === 'wo').rows[0].go(); v = c.renderVals();
console.log('   oldest WO row → unit', v.panel.title, '| crumbs', v.panel.crumbs.map((x) => x.label).join(' › '));
const wo = v.panel.unit.issues.find((i) => i.kind === 'wo'); wo.actions.find((a) => a.label === 'RESOLVED').fn(); v = c.renderVals();
console.log('   resolved one → unit issues now', v.panel.unit.count, '| toast', c.state.toast);
c.setState({ pickedB: null, pickedU: null }); v = c.renderVals();
const sec = v.panel.sections.find((s) => s.key === 'wo'); sec.toggle(); v = c.renderVals();
console.log('   collapse W/O section → open:', v.panel.sections.find((s) => s.key === 'wo').isOpen);
v.panel.crumbs[0].go(); v = c.renderVals(); console.log('   breadcrumb ALL PROPERTIES → level all:', v.panel.isAll);
